version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: smart-parking-db
    environment:
      POSTGRES_DB: parkingdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - parking-postgres-data:/var/lib/postgresql/data
    networks:
      - parking-net

  redis:
    image: redis:7
    container_name: smart-parking-redis
    ports:
      - "6379:6379"
    networks:
      - parking-net

volumes:
  parking-postgres-data:

networks:
  parking-net:
